---
- name: "Install prerequisites with APT"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - ca-certificates
      - curl
  become: true

- name: "Install Docker gpg key"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      wget -O- https://download.docker.com/linux/ubuntu/gpg > /usr/share/keyrings/docker.asc
    executable: /bin/bash
    creates: /usr/share/keyrings/docker.asc
  become: true

- name: "Add Docker APT repo"
  ansible.builtin.apt_repository:
    # TODO: support other architectures (not needed rn)
    repo: >-
      deb [
        arch=amd64
        signed-by=/usr/share/keyrings/docker.asc
      ]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  become: true

- name: "Install Docker packages"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true

- name: "Add user to docker group for user {{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
  become: true
